// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "DRSAttributeSet.h"
#include "AbilitySystemComponent.h"
#include "DRSCharacterAttributeSet.generated.h"

/**
 * Attribute set containing character-specific resources for the Dual Resource System.
 *
 * These attributes are represented with FGameplayAttributeData so they can be modified by
 * Gameplay Effects and referenced through the generated ATTRIBUTE_ACCESSORS helpers.
 * This class currently defines health, mana, and their regeneration rates; it does not define
 * max values, clamping rules, or replication behavior by itself.
 */
UCLASS()
class DUALRESOURCESYSTEM_API UDRSCharacterAttributeSet : public UDRSAttributeSet
{
	GENERATED_BODY()
	
public:
	/** Creates the character attribute set. */
	UDRSCharacterAttributeSet();
	
	/** Current health resource value for the character. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Attributes")
	FGameplayAttributeData Health;
	ATTRIBUTE_ACCESSORS(UDRSCharacterAttributeSet, Health)
	
	/** Amount of health regenerated by gameplay systems that consume this attribute. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Attributes")
	FGameplayAttributeData HealthRegenRate;
	ATTRIBUTE_ACCESSORS(UDRSCharacterAttributeSet, HealthRegenRate)

	/** Current mana resource value for the character. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Attributes")
	FGameplayAttributeData Mana;
	ATTRIBUTE_ACCESSORS(UDRSCharacterAttributeSet, Mana)
	
	/** Amount of mana regenerated by gameplay systems that consume this attribute. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Attributes")
	FGameplayAttributeData ManaRegenRate;
	ATTRIBUTE_ACCESSORS(UDRSCharacterAttributeSet, ManaRegenRate)
};
