// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "DRSAttributeSet.h"
#include "AbilitySystemComponent.h"
#include "DRSCharacterAttributeSet.generated.h"

/**
 * Attribute set containing character-specific resources for the Dual Resource System.
 *
 * These attributes are represented with FGameplayAttributeData so they can be modified by
 * Gameplay Effects and referenced through the generated ATTRIBUTE_ACCESSORS helpers.
 * This class currently defines health, mana, and their regeneration rates; it does not define
 * max values, clamping rules, or replication behavior by itself.
 */
UCLASS()
class DUALRESOURCESYSTEM_API UDRSCharacterAttributeSet : public UDRSAttributeSet
{
	GENERATED_BODY()
	
public:
	// Delegate when health changes due to damage/healing, some information may be missing on the client
	mutable FDRSAttributeEvent OnHealthChanged;

	// Delegate to broadcast when the health attribute reaches zero
	mutable FDRSAttributeEvent OnOutOfHealth;
	
	/** Creates the character attribute set. */
	UDRSCharacterAttributeSet();
	
	/**
	 *	Called just before modifying the value of an attribute. AttributeSet can make additional modifications here. Return true to continue, or false to throw out the modification.
	 *	Note this is only called during an 'execute'. E.g., a modification to the 'base value' of an attribute. It is not called during an application of a GameplayEffect, such as a 5 second +10 movement speed buff.
	 */	
	virtual bool PreGameplayEffectExecute(FGameplayEffectModCallbackData &Data) override;
	
	/**
	 *	Called just after a GameplayEffect is executed to modify the base value of an attribute. No more changes can be made.
	 *	Note this is only called during an 'execute'. E.g., a modification to the 'base value' of an attribute. It is not called during an application of a GameplayEffect, such as a 5 second +10 movement speed buff.
	 */
	virtual void PostGameplayEffectExecute(const FGameplayEffectModCallbackData &Data) override;
	
	ATTRIBUTE_ACCESSORS(UDRSCharacterAttributeSet, Health)
	ATTRIBUTE_ACCESSORS(UDRSCharacterAttributeSet, HealthRegenRate)
	ATTRIBUTE_ACCESSORS(UDRSCharacterAttributeSet, CriticalHealth)
	ATTRIBUTE_ACCESSORS(UDRSCharacterAttributeSet, Mana)
	ATTRIBUTE_ACCESSORS(UDRSCharacterAttributeSet, ManaRegenRate)
	ATTRIBUTE_ACCESSORS(UDRSCharacterAttributeSet, ResourceCost)
	
protected:
	/** Current health resource value for the character. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Attributes")
	FGameplayAttributeData Health;
	
	/** Amount of health regenerated by gameplay systems that consume this attribute. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Attributes")
	FGameplayAttributeData HealthRegenRate;

	/** Threshold for health value that triggers reserve health mechanics in gameplay systems that consume this attribute. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Attributes")
	FGameplayAttributeData CriticalHealth;
	
	/** Current mana resource value for the character. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Attributes")
	FGameplayAttributeData Mana;
	
	/** Amount of mana regenerated by gameplay systems that consume this attribute. */
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Attributes")
	FGameplayAttributeData ManaRegenRate;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = "Attributes")
	FGameplayAttributeData ResourceCost;
	
private:
	void HandleCostExecution(const FGameplayEffectModCallbackData& Data);
	void CheckForHealthChange(const FGameplayEffectModCallbackData& Data);
	static bool IsOverdrawEnabled(const FGameplayEffectModCallbackData& Data);
	
	void ApplyHealthCost(float Amount);
	void ApplyManaCost(float Amount);
	
	float HealthPreAttributeChange;
};
